tabuada = int(input('Digite a tabuada que desejas: '))

print ('{0} X 1 = {1}'.format(tabuada, tabuada*1))
print ('{0} X 2 = {1}'.format(tabuada, tabuada*2))
print ('{0} X 3 = {1}'.format(tabuada, tabuada*3))
print ('{0} X 4 = {1}'.format(tabuada, tabuada*4))
print ('{0} X 5 = {1}'.format(tabuada, tabuada*5))
print ('{0} X 6 = {1}'.format(tabuada, tabuada*6))
print ('{0} X 7 = {1}'.format(tabuada, tabuada*7))
print ('{0} X 8 = {1}'.format(tabuada, tabuada*8))
print ('{0} X 9 = {1}'.format(tabuada, tabuada*9))
print ('{0} X 10 = {1}'.format(tabuada, tabuada*10))
print ('{0} X 11 = {1}'.format(tabuada, tabuada*11))
print ('{0} X 12 = {1}'.format(tabuada, tabuada*12))