# -*- coding: utf-8 -*-
"""AP_08.ipynb

Automatically generated by Colab.


# Vamos aplicar o que aprendemos sobre regressões lineares
*   Complete com o código em falta
*   Sempre que necessário, **substitua** ___

---

dataset: [fonte](https://www.kaggle.com/datasets/quantbruce/real-estate-price-prediction)

---

Corra a primeira célula de código para obter o dataframe com que vamos trabalhar
"""

# faça o upload do ficheiro csv associado à atividade

# vamos importar a biblioteca
import pandas as pd
import numpy as np

# vamos importar o dataframe do ficheiro .csv
df_real_estate = (pd
                  .read_csv("Real estate.csv")
                  .drop(["No",
                         "X1 transaction date",
                         "X4 number of convenience stores"], axis = 1))

# veja as 5 primeiras linhas do dataframe
df_real_estate.head()
# veja a forma do dataframe: quantas linhas, quantas colunas?
df_real_estate.shape
# veja a informação sobre o dataframe
df_real_estate.info()
# veja a descrição das variáveis numéricas
df_real_estate.describe()

# importe o matplotlib.pyplot
import ___ as ___

___.style.use('ggplot')

x_variable = ___["X5 latitude"]
___ = ___["Y house price of unit area"]

___.___(___, ___, color = 'b')
___.___("preço do m2 de habitação")
___.___('latitude')
___.show()

# defina a variável alvo ("Y house price of unit area")
target_variable = ___

# train_test split usando a função train_test_split
___ = ___
___ = ___

from ___ import ___
___, ___, ___, ___ = ___(___, ___, ___ = 0.3, ___ = 12)

# escolha "X5 latitude" como variável independente
x_variable = 'X5 latitude'
X_1_feature = ___[[___]]

# importe o modelo
from ___ import ___
lin_reg = ___()
lin_reg.___(___, ___)

# faça previsão para os pontos de teste
___ = ___.___()

# veja os coeficientes da regressão
m = ___.___
b = ___.___
print("m: {}; b: {}".format(m , b))

# verifique o r2 (round -> 3)
print("r2: {}".format(___.___(___, ___).___))

# visualize o resultado para o teste
___.___(___, ___, color = 'k')
___.___(___, ___, color = 'r')
___.ylabel("preço do m2 de habitação")
___.xlabel('latitude')
___.show()

# vamos codificar o nome das variáveis
columns_names = ["x1", "x2", "x3", "x4", "y"]
df_real_estate.columns = columns_names

# importe o modelo de regressão linear
from ___ import ___
lin_reg_all = ___(___)
lin_reg_all.___(___, ___)
y_pred = ___.___(___)

# verifique o r2 (round -> 3)
lin_reg_all.___(___, ___).___

# importe o modelo de Ridge
from sklearn.linear_model import Ridge

# considere alpha = 0.3
ridge_reg = ___(___)
___.___
y_pred_ridge = ___

# verifique o r2 (round -> 3)
ridge_reg.___

# importe o modelo de Lasso
from ___ import ___

# considere alpha = 0.5
lasso_reg = ___(___)
lasso_reg.___(___)
y_pred_lasso = lasso_reg.___(___)

# verifique o r2 (round -> 3)
lasso_reg.___.___